"""
constants.py
This module contains the constants used in the nfl_stats project.
Constants:
- QB_STATS: A list of quarterback statistics.
- RB_STATS: A list of running back statistics.
- WR_STATS: A list of wide receiver statistics.
- TE_STATS: A list of tight end statistics.
- DEF_STATS: A list of defense statistics.
"""

import os
from pathlib import Path

# Project directory configurations
ROOT_DIR = Path(__file__).parent.parent
DATA_PATH = os.path.join(ROOT_DIR, "data")

POSITION_STATS = {
    "ALL": [
        "player_id",
        "name",
        "position",
        "team",
        "season",
        "gp",
        "gs",
        "snp",
        "pass_yd",
        "pass_td",
        "pass_fd",
        "pass_2pt",
        "pass_int",
        "pass_int_td",
        "pass_cmp",
        "pass_inc",
        "pass_att",
        "pass_sack",
        "pass_cmp_40p",
        "pass_td_40p",
        "pass_td_50p",
        "rush_yd",
        "rush_td",
        "rush_fd",
        "rush_2pt",
        "rush_att",
        "rush_40p",
        "rush_td_40p",
        "rush_td_50p",
        "rec",
        "rec_yd",
        "rec_td",
        "rec_fd",
        "rec_2pt",
        "rec_0_4",
        "rec_5_9",
        "rec_10_19",
        "rec_20_29",
        "rec_30_39",
        "rec_40p",
        "rec_td_40p",
        "rec_td_50p",
        "bonus_rec_rb",
        "bonus_rec_wr",
        "bonus_rec_te",
        "fgm",
        "fgm_0_19",
        "fgm_20_29",
        "fgm_30_39",
        "fgm_40_49",
        "fgm_50_59",
        "fgm_50p",
        "fgm_60p",
        "fgm_yds",
        "fgm_yds_over_30",
        "xpm",
        "fgmiss",
        "fgmiss_0_19",
        "fgmiss_20_29",
        "fgmiss_30_39",
        "fgmiss_40_49",
        "fgmiss_50_59",
        "fgmiss_50p",
        "fgmiss_60p",
        "xpmiss",
        "st_td",
        "st_ff",
        "st_fum_rec",
        "st_tkl_solo",
        "pr_yd",
        "kr_yd",
        "fum",
        "fum_lost",
        "fum_rec_td",
        "bonus_rush_yd_100",
        "bonus_rush_yd_200",
        "bonus_rec_yd_100",
        "bonus_rec_yd_200",
        "bonus_pass_yd_300",
        "bonus_pass_yd_400",
        "bonus_rush_rec_yd_100",
        "bonus_rush_rec_yd_200",
        "bonus_pass_comp_25",
        "bonus_rush_att_20",
        "bonus_fd_rb",
        "bonus_fd_wr",
        "bonus_fd_te",
        "bonus_fd_qb",
        "def_td",
        "pts_allow_0",
        "pts_allow_1_6",
        "pts_allow_7_13",
        "pts_allow_14_20",
        "pts_allow_21_27",
        "pts_allow_28_34",
        "pts_allow_35p",
        "pts_allow",
        "yds_allow_0_100",
        "yds_allow_100_199",
        "yds_allow_200_299",
        "yds_allow_300_349",
        "yds_allow_350_399",
        "yds_allow_400_449",
        "yds_allow_450_499",
        "yds_allow_500_549",
        "yds_allow_550p",
        "yds_allow",
        "def_3_and_out",
        "def_4_and_stop",
        "qb_hit",
        "sack",
        "sack_yd",
        "int",
        "int_ret_yd",
        "fum_rec",
        "fum_ret_yd",
        "tkl_loss",
        "tkl_ast",
        "tkl_solo",
        "tkl",
        "safe",
        "ff",
        "blk_kick",
        "def_forced_punts",
        "def_pass_def",
        "def_2pt",
        "fg_ret_yd",
        "blk_kick_ret_yd",
        "def_st_td",
        "def_st_ff",
        "def_st_fum_rec",
        "def_st_tkl_solo",
        "def_pr_yd",
        "def_kr_yd",
    ],
}
